name: "PNPM setup"
author: "Arbeidstilsynet"
description: "Setups Node and PNPM, runs audit and install"

inputs:
  node-version:
    description: "Node.js version to use"
    default: "24.x"
    required: false
  working-directory:
    description: "Working directory containing package.json and pnpm-lock.yaml"
    default: "."
    required: false
  skip-install:
    description: "Skip pnpm install step"
    default: "false"
    required: false
  skip-audit:
    description: "Skip pnpm audit step"
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        package_json_file: "${{ inputs.working-directory }}/package.json"
        cache: true

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "${{ inputs.node-version }}"
        registry-url: "https://registry.npmjs.org"

    - shell: bash
      run: pnpm --version
      working-directory: ${{ inputs.working-directory }}

    - shell: bash
      if: ${{ inputs.skip-audit != 'true' }}
      run: pnpm audit
      working-directory: ${{ inputs.working-directory }}

    - shell: bash
      if: ${{ inputs.skip-install != 'true' }}
      run: pnpm install
      working-directory: ${{ inputs.working-directory }}

    - name: "List packages"
      shell: bash
      if: ${{ inputs.skip-install != 'true' }}
      run: pnpm ls -r --depth 0
      working-directory: ${{ inputs.working-directory }}
