name: "PNPM setup"
author: "Arbeidstilsynet"
description: "Setups Node and PNPM, runs audit and install"

inputs:
  node-version:
    description: "Node.js version to use"
    default: "24.x"
    required: false
  working-directory:
    description: "Working directory containing package.json"
    default: "."
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        package_json_file: "${{ inputs.working-directory }}/package.json"

    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: "${{ inputs.node-version }}"
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - shell: bash
      run: pnpm --version
      working-directory: ${{ inputs.working-directory }}
    - shell: bash
      run: pnpm audit
      working-directory: ${{ inputs.working-directory }}
    - shell: bash
      run: pnpm install
      working-directory: ${{ inputs.working-directory }}
    - name: "List packages"
      shell: bash
      run: pnpm ls -r --depth 0
      working-directory: ${{ inputs.working-directory }}
