name: "PNPM setup"
author: "Arbeidstilsynet"
description: "Setups Node and PNPM, runs audit and install"

inputs:
  node-version:
    description: "Node.js version to use"
    default: "24.x"
    required: false
  working-directory:
    description: "Working directory containing package.json and pnpm-lock.yaml"
    default: "."
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        package_json_file: "${{ inputs.working-directory }}/package.json"

    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: "${{ inputs.node-version }}"
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"
        cache-dependency-path: "${{ inputs.working-directory }}/pnpm-lock.yaml"

    - shell: bash
      run: pnpm --version
      working-directory: ${{ inputs.working-directory }}
    - shell: bash
      run: pnpm audit
      working-directory: ${{ inputs.working-directory }}
    - shell: bash
      run: pnpm install
      working-directory: ${{ inputs.working-directory }}
    - name: "List packages"
      shell: bash
      run: pnpm ls -r --depth 0
      working-directory: ${{ inputs.working-directory }}
